9 add project proposal document
peiva-git/deep_learning_project pull request #10
Opened 2023-10-25 09:12 UTC by FedericoCalandra

Added project proposal .pdf and updated README file

2023-10-25 09:20 UTC, peiva-git commented
E il codice LaTeX per la nuova copertina del pdf generato?
Secondo me possiamo togliere anche il sommario, tanto non serve molto.

2023-10-25 09:35 UTC, FedericoCalandra commented
Risolto. Ho rimosso il sommario e aggiornato la cartella report.

2023-10-30 09:15 UTC, peiva-git requested changes
Vedi commenti

2023-10-30 10:02 UTC, FedericoCalandra commented
Dovrei aver sistemato

2023-10-30 10:10 UTC, peiva-git approved these changes

2023-10-30 10:10 UTC, merged