14 add renoir dataset
peiva-git/deep_learning_project pull request #40
Opened 2023-11-04 12:28 UTC by FedericoCalandra

Ho aggiunto la classe RENOIRDatasetBuilder. Costruisce il test set per valutare le performance dei modelli complessi che andremo ad implementare. 

Per farlo funzionare è necessario:
1) scaricare il dataset da questo link (va bene uno tra Canon T3i e Xiaomi Mi3 o entrambi, versione aligned)
2) decomprimere la cartella
3) il percorso della cartella va passato al costruttore della classe: `__init__(self, dataset_folder, dataset_type)`
4) dataset_type può essere 'Mi3_Aligned' o 'T3i_Aligned'

Nota: il dataset è molto grande, non sono sicuro di quale sia il modo migliore per importarlo (su GitHub?)

2023-11-04 23:31 UTC, peiva-git commented
Su GitHub non penso sia fattibile. Un modo sarebbe caricarlo su [Kaggle](https://www.kaggle.com/) e usare dopo le loro API REST per recuperarlo. Non ho mai provato ma credo non sia troppo difficile.
Altrimenti, più semplicemente, lasciamo che bisogna scaricarlo manualmente.

2023-11-04 23:36 UTC, peiva-git commented
Temo però che leggere tutte le immagini del dataset (ovvero caricarle in memoria) al momento della creazione dell'istanza della classe non funzionerà, perché il dataset è troppo grande. Bisognerà utilizzare la classe [Sequence](https://www.tensorflow.org/api_docs/python/tf/keras/utils/Sequence) di Keras.

2023-11-04 23:37 UTC, peiva-git requested changes
Vedi commento in #40

2023-11-05 12:10 UTC, FedericoCalandra commented
Ho fatto un po' di prove e funziona bene ma il caricamento in memoria è effettivamente piuttosto lento (non meno di un paio di minuti) e satura completamente i miei poveri 8 GB di ram. Seguo il consiglio e implemento una nuova versione di RENOIRDatasetBuilder usando la classe Sequence di Keras.

2023-11-05 13:39 UTC, FedericoCalandra commented
Ho aggiunto la nuova versione. Purtroppo non ho notato significative differenze nei tempi di esecuzione ma forse è dovuto al fatto che semplicemente ho un PC vecchio

2023-11-05 16:20 UTC, peiva-git commented on dlproject/data/renoir_dataset.py
> +        return math.ceil(len(self.test_data_paths) / self.batch_size)
Non è necessario usare np.ceil

2023-11-05 16:21 UTC, peiva-git commented on dlproject/data/renoir_dataset.py
> +        high = min(low + self.batch_size, len(self.test_data_paths))
Nel caso in cui l'ultimo batch non abbia dimensione `batch_size`. Non necessariamente il numero di immagini è divisibile per `batch_size`.

2023-11-05 16:21 UTC, peiva-git commented on requirements.txt
> +setuptools~=60.2.0
Perché non l'ultima versione 68.2.2?

2023-11-05 16:22 UTC, peiva-git requested changes
Ben fatto, ho applicato alcune correzioni, ho solo un dubbio prima di approvare, vedi commenti.

2023-11-06 10:49 UTC, FedericoCalandra commented on requirements.txt
> +setuptools~=60.2.0
Risolto

2023-11-06 11:00 UTC, peiva-git approved these changes
👍

2023-11-06 11:01 UTC, merged